services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PBePqAltHfEwiGBVZfKAArZKznbBIDTN
      POSTGRES_DB: railway
    ports:
      - "33909:33909"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://yamanote.proxy.rlwy.net:33909/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: PBePqAltHfEwiGBVZfKAArZKznbBIDTN
    ports:
      - "4000:4000"
    depends_on:
    - db